# numpy broadcasting rules

## what broadcasting is

broadcasting is the mechanism numpy uses to perform operations on arrays of different shapes.

it allows numpy to automatically expand smaller arrays so they can match larger ones during operations.

---

## why broadcasting exists

without broadcasting you would need to manually reshape or copy arrays.

broadcasting makes operations efficient and avoids unnecessary memory usage.

---

## core rules of broadcasting

when operating on two arrays, numpy compares their shapes from right to left.

### rule 1

dimensions are compatible if they are equal  

or one of them is 1  

---

### rule 2

if one dimension is 1, it is stretched to match the other dimension  

this expansion is virtual and does not copy data in memory  

---

### rule 3

if dimensions do not match and neither is 1, broadcasting fails  

---

## step by step comparison

given two shapes:

A shape = (4, 3)  
B shape = (3,)  

align from right:

A = (4, 3)  
B = (1, 3)  

comparison:

3 matches 3  
1 expands to 4  

result shape becomes:

(4, 3)  

---

## example 1 row broadcasting

```python
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

result = A + B
print(result)

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(2, 18, size=(3, 4))
arr

array([[ 8, 12,  8,  4],
       [15, 16,  3, 16],
       [14,  2, 13,  4]])

In [4]:
# We would like to subtract the largest value per row and per column to accomplish this cleanly, we male use of the broadcasting concept

arr.max()

np.int64(16)

In [5]:
arr.max(axis=0)

array([15, 16, 13, 16])

In [6]:
arr.max(axis=1)

array([12, 16, 14])

In [8]:
arr.max(axis=1, keepdims=True)

array([[12],
       [16],
       [14]])

In [9]:
arr.max(axis=0, keepdims=True)

array([[15, 16, 13, 16]])

In [10]:
arr - arr.max(axis=0, keepdims=True)

array([[ -7,  -4,  -5, -12],
       [  0,   0, -10,   0],
       [ -1, -14,   0, -12]])

In [11]:
arr - arr.max(axis=1, keepdims=True)

array([[ -4,   0,  -4,  -8],
       [ -1,   0, -13,   0],
       [  0, -12,  -1, -10]])

In [12]:
# This concept is usefull for the understand how biases are added up after applying the dot products to the weights and the inputs