In [191]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
import random as rd

In [184]:
dataset = load_iris(as_frame=True)
df_f = pd.DataFrame(dataset.data, columns=dataset.feature_names) 
df_f.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [185]:
df_t = pd.Series(dataset.target, name="Target")
df_t.head()

0    0
1    0
2    0
3    0
4    0
Name: Target, dtype: int64

In [186]:
df = df_f.join(df_t, how='left')
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [187]:
counts = df_t.value_counts()

counts.values.tolist()

[50, 50, 50]

In [188]:
c_indexes = counts.index.tolist()

In [189]:
def split_dataset(df, k:int, strat:bool, rand:bool):
    pair = []
    r_indexes = [i for i in range(len(df))]
    
    indexes = []
    for c in c_indexes:
        indexes.append(df[df == c].index.tolist())

    if strat:
        if rand:
            indexes = [np.random.permutation(i) for i in indexes]
        indicies = [np.array_split(arr, k) for arr in indexes]
        indexes = []
        for (arr1, arr2, arr3) in zip(*indicies):
            indexes.append(np.concat((arr1, arr2, arr3)))
    else:
        if rand:
            rd.shuffle(r_indexes)
        indexes = np.array_split(r_indexes, k)

    for i in range(len(indexes)):
        test = indexes[i]
        train = np.delete(indexes, i, axis=0)
        pair.append((test, train))
    return pair

In [193]:
evaluation = {}
splits = split_dataset(df_t, 5, True, True)
for n in range(3, 13):
    scores = []
    for tp in splits:
        model = KNeighborsClassifier(n_neighbors=n)
        for arr in tp[1]:
            model.fit(df_f.iloc[arr], df_t.iloc[arr])
        scores.append(model.score(df_f.iloc[tp[0]], df_t.iloc[tp[0]]))

        cf = confusion_matrix(df_t.iloc[tp[0]], model.predict(df_f.iloc[tp[0]]))
        print(cf)
    evaluation[n] = float(np.mean(scores))

evaluation

[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  4  6]]
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]
[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]
[[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  4  6]]
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
[

{3: 0.9466666666666667,
 4: 0.9400000000000001,
 5: 0.9466666666666667,
 6: 0.9266666666666665,
 7: 0.9400000000000001,
 8: 0.9199999999999999,
 9: 0.9400000000000001,
 10: 0.9,
 11: 0.9200000000000002,
 12: 0.9066666666666666}