In [1]:
import numpy as np

# Understanding numpy linspace

## What linspace does

numpy linspace generates a sequence of evenly spaced numbers between a start value and an end value.

You define:

* start value
* end value
* number of points

numpy computes values that are equally spaced across that interval.

---

## Basic example

```python
import numpy as np

np.linspace(0, 10, 5)
```

**Output**

```python
[0.  2.5  5.  7.5 10.]
```

This creates 5 values starting at 0 and ending at 10.

---

## How it works internally

The spacing between values is calculated as:

step = (end minus start) divided by (number of points minus 1)

### Example

* start = 0
* end = 10
* points = 5

step = (10 minus 0) divided by (5 minus 1)
step = 10 divided by 4
step = 2.5

### Generated values

* 0
* 0 plus 2.5
* 0 plus 2.5 times 2
* 0 plus 2.5 times 3
* 0 plus 2.5 times 4

---

## Including or excluding the end value

By default, the end value is included.

```python
np.linspace(0, 10, 5)
```

### Excluding the end value

```python
np.linspace(0, 10, 5, endpoint=False)
```

This changes the spacing so the values stop before 10.

---

## Returning the step size

You can also get the step value:

```python
values, step = np.linspace(0, 10, 5, retstep=True)
```

### Output

**values**

```python
[0.  2.5  5.  7.5 10.]
```

**step**

```python
2.5
```

---

## Data type control

You can control the output type:

```python
np.linspace(0, 10, 5, dtype=int)
```

---

## linspace vs arange

### linspace

* you control number of values

### arange

* you control step size

### Example

```python
np.linspace(0, 10, 5)
```

```python
np.arange(0, 10, 2)
```

---

## Summary

* linspace splits a range into equal parts based on how many values you want
* it guarantees inclusion of the end value unless changed
* it is ideal when you need a fixed number of evenly spaced samples


In [10]:
np.linspace(1, 6, 6)

array([1., 2., 3., 4., 5., 6.])

In [11]:
np.linspace(1, 50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [12]:
np.linspace(-1, 1, 20)

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [13]:
np.linspace(1, -1, 20)

array([ 1.        ,  0.89473684,  0.78947368,  0.68421053,  0.57894737,
        0.47368421,  0.36842105,  0.26315789,  0.15789474,  0.05263158,
       -0.05263158, -0.15789474, -0.26315789, -0.36842105, -0.47368421,
       -0.57894737, -0.68421053, -0.78947368, -0.89473684, -1.        ])

# Understanding numpy arange

## What arange does

numpy arange generates a sequence of numbers using a fixed step size.

You define:

* start value
* end value
* step size

numpy then builds values by repeatedly adding the step until it reaches the end.

---

## Basic example

```python id="p1x8sa"
import numpy as np

np.arange(0, 10, 2)
```

**Output**

```python id="k9v2lm"
[0 2 4 6 8]
```

This creates values starting at 0 and increases by 2 each time.

---

## How it works internally

The sequence is built like this:

value = start

next value = value plus step

repeat until the value is greater than or equal to the end

### Example

* start = 0
* end = 10
* step = 2

### Generated values

* 0
* 2
* 4
* 6
* 8

10 is not included because the sequence stops before reaching the end.

---

## End value behavior

The end value is not included.

```python id="r8gqxo"
np.arange(0, 10, 2)
```

Even though 10 fits the pattern, it is excluded because arange stops before the end.

---

## Floating point steps

arange can use decimal steps, but this can introduce precision issues.

```python id="a0m9tq"
np.arange(0, 1, 0.2)
```

Possible output:

```python id="6q4r8n"
[0.  0.2 0.4 0.6 0.8]
```

Sometimes the final value may not be exact due to floating point rounding.

---

## Data type control

You can control the output type:

```python id="d7n2yk"
np.arange(0, 10, 2, dtype=float)
```

---

## When to use arange

Use arange when you care about the step size between values.

---

## arange vs linspace

### arange

* you control step size
* end is usually excluded
* can have floating point precision issues

### linspace

* you control number of values
* end is included by default
* more stable for decimal spacing

### Example

```python id="l1z8pd"
np.arange(0, 10, 2)
```

```python id="c5h3fw"
np.linspace(0, 10, 5)
```

---

## Summary

* arange builds sequences using a fixed step size
* it stops before reaching the end value
* it is best when you need consistent increments between values
* be careful when using decimal step sizes due to precision limitations


In [17]:
np.arange(1,0)

array([], dtype=int64)

In [18]:
np.arange(1, 50, 60)

array([1])

In [23]:
np.arange(0, 50, 50)

array([0])

In [27]:
np.arange(0, 200, 5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195])

In [32]:
np.arange(61)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

# Understanding numpy reshape

## What reshape does

numpy reshape changes the shape of an array without changing its data.

It reorganizes how the data is viewed in dimensions.

You define:

* the original array
* the new shape

The total number of elements must remain the same.

---

## Basic example

```python
import numpy as np

arr = np.arange(6)
reshaped = arr.reshape(2, 3)

print(reshaped)
```

**Output**

```python
[[0 1 2]
 [3 4 5]]
```

The data is the same, only arranged into 2 rows and 3 columns.

---

## Key rule

number of elements must match

Example:

* original array has 6 elements
* new shape must also contain 6 elements

Valid shapes:

* 2 by 3
* 3 by 2
* 1 by 6
* 6 by 1

Invalid:

* 4 by 2  because it requires 8 elements

---

## How reshape works internally

reshape reads the array in row order and fills the new shape in the same order.

Original:

```python
[0 1 2 3 4 5]
```

Reshaped to 2 by 3:

```python
[[0 1 2]
 [3 4 5]]
```

---

## Using negative one

You can let numpy infer one dimension using negative one.

```python
arr = np.arange(6)

reshaped = arr.reshape(2, -1)
print(reshaped)
```

**Output**

```python
[[0 1 2]
 [3 4 5]]
```

numpy automatically calculates the missing dimension.

---

## Flattening an array

Convert multi dimensional array back to one dimension:

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.reshape(-1)
print(flat)
```

**Output**

```python
[1 2 3 4 5 6]
```

---

## Reshaping to higher dimensions

```python
arr = np.arange(8)

reshaped = arr.reshape(2, 2, 2)
print(reshaped)
```

**Output**

```python
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
```

---

## Common patterns

Row vector

```python
arr.reshape(1, -1)
```

Column vector

```python
arr.reshape(-1, 1)
```

---

## reshape vs resize

reshape:

* returns a new view or array
* does not modify original shape

resize:

* modifies the original array
* can change total number of elements

---

## Summary

* reshape changes how data is arranged, not the data itself
* total number of elements must remain constant
* negative one allows automatic dimension calculation
* useful for preparing data for models and matrix operations


In [70]:
arr = np.linspace(0, 350, 72)
arr

array([  0.        ,   4.92957746,   9.85915493,  14.78873239,
        19.71830986,  24.64788732,  29.57746479,  34.50704225,
        39.43661972,  44.36619718,  49.29577465,  54.22535211,
        59.15492958,  64.08450704,  69.01408451,  73.94366197,
        78.87323944,  83.8028169 ,  88.73239437,  93.66197183,
        98.5915493 , 103.52112676, 108.45070423, 113.38028169,
       118.30985915, 123.23943662, 128.16901408, 133.09859155,
       138.02816901, 142.95774648, 147.88732394, 152.81690141,
       157.74647887, 162.67605634, 167.6056338 , 172.53521127,
       177.46478873, 182.3943662 , 187.32394366, 192.25352113,
       197.18309859, 202.11267606, 207.04225352, 211.97183099,
       216.90140845, 221.83098592, 226.76056338, 231.69014085,
       236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
       256.33802817, 261.26760563, 266.1971831 , 271.12676056,
       276.05633803, 280.98591549, 285.91549296, 290.84507042,
       295.77464789, 300.70422535, 305.63380282, 310.56

In [73]:
arr.reshape(4, -1)

array([[  0.        ,   4.92957746,   9.85915493,  14.78873239,
         19.71830986,  24.64788732,  29.57746479,  34.50704225,
         39.43661972,  44.36619718,  49.29577465,  54.22535211,
         59.15492958,  64.08450704,  69.01408451,  73.94366197,
         78.87323944,  83.8028169 ],
       [ 88.73239437,  93.66197183,  98.5915493 , 103.52112676,
        108.45070423, 113.38028169, 118.30985915, 123.23943662,
        128.16901408, 133.09859155, 138.02816901, 142.95774648,
        147.88732394, 152.81690141, 157.74647887, 162.67605634,
        167.6056338 , 172.53521127],
       [177.46478873, 182.3943662 , 187.32394366, 192.25352113,
        197.18309859, 202.11267606, 207.04225352, 211.97183099,
        216.90140845, 221.83098592, 226.76056338, 231.69014085,
        236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
        256.33802817, 261.26760563],
       [266.1971831 , 271.12676056, 276.05633803, 280.98591549,
        285.91549296, 290.84507042, 295.77464789, 300.704

In [74]:
arr.reshape(3, -1)

array([[  0.        ,   4.92957746,   9.85915493,  14.78873239,
         19.71830986,  24.64788732,  29.57746479,  34.50704225,
         39.43661972,  44.36619718,  49.29577465,  54.22535211,
         59.15492958,  64.08450704,  69.01408451,  73.94366197,
         78.87323944,  83.8028169 ,  88.73239437,  93.66197183,
         98.5915493 , 103.52112676, 108.45070423, 113.38028169],
       [118.30985915, 123.23943662, 128.16901408, 133.09859155,
        138.02816901, 142.95774648, 147.88732394, 152.81690141,
        157.74647887, 162.67605634, 167.6056338 , 172.53521127,
        177.46478873, 182.3943662 , 187.32394366, 192.25352113,
        197.18309859, 202.11267606, 207.04225352, 211.97183099,
        216.90140845, 221.83098592, 226.76056338, 231.69014085],
       [236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
        256.33802817, 261.26760563, 266.1971831 , 271.12676056,
        276.05633803, 280.98591549, 285.91549296, 290.84507042,
        295.77464789, 300.70422535, 30

In [84]:
ar = arr.reshape(3, 1, -1)
ar

array([[[  0.        ,   4.92957746,   9.85915493,  14.78873239,
          19.71830986,  24.64788732,  29.57746479,  34.50704225,
          39.43661972,  44.36619718,  49.29577465,  54.22535211,
          59.15492958,  64.08450704,  69.01408451,  73.94366197,
          78.87323944,  83.8028169 ,  88.73239437,  93.66197183,
          98.5915493 , 103.52112676, 108.45070423, 113.38028169]],

       [[118.30985915, 123.23943662, 128.16901408, 133.09859155,
         138.02816901, 142.95774648, 147.88732394, 152.81690141,
         157.74647887, 162.67605634, 167.6056338 , 172.53521127,
         177.46478873, 182.3943662 , 187.32394366, 192.25352113,
         197.18309859, 202.11267606, 207.04225352, 211.97183099,
         216.90140845, 221.83098592, 226.76056338, 231.69014085]],

       [[236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
         256.33802817, 261.26760563, 266.1971831 , 271.12676056,
         276.05633803, 280.98591549, 285.91549296, 290.84507042,
         295.774647

In [76]:
ar[0]

array([[  0.        ,   4.92957746,   9.85915493,  14.78873239,
         19.71830986,  24.64788732,  29.57746479,  34.50704225,
         39.43661972,  44.36619718,  49.29577465,  54.22535211,
         59.15492958,  64.08450704,  69.01408451,  73.94366197,
         78.87323944,  83.8028169 ],
       [ 88.73239437,  93.66197183,  98.5915493 , 103.52112676,
        108.45070423, 113.38028169, 118.30985915, 123.23943662,
        128.16901408, 133.09859155, 138.02816901, 142.95774648,
        147.88732394, 152.81690141, 157.74647887, 162.67605634,
        167.6056338 , 172.53521127]])

In [77]:
ar[0,0]

array([ 0.        ,  4.92957746,  9.85915493, 14.78873239, 19.71830986,
       24.64788732, 29.57746479, 34.50704225, 39.43661972, 44.36619718,
       49.29577465, 54.22535211, 59.15492958, 64.08450704, 69.01408451,
       73.94366197, 78.87323944, 83.8028169 ])

In [78]:
ar[0, 0, 0]

np.float64(0.0)

In [86]:
ar = arr.reshape(2, 3, 2, -1)
ar

array([[[[  0.        ,   4.92957746,   9.85915493,  14.78873239,
           19.71830986,  24.64788732],
         [ 29.57746479,  34.50704225,  39.43661972,  44.36619718,
           49.29577465,  54.22535211]],

        [[ 59.15492958,  64.08450704,  69.01408451,  73.94366197,
           78.87323944,  83.8028169 ],
         [ 88.73239437,  93.66197183,  98.5915493 , 103.52112676,
          108.45070423, 113.38028169]],

        [[118.30985915, 123.23943662, 128.16901408, 133.09859155,
          138.02816901, 142.95774648],
         [147.88732394, 152.81690141, 157.74647887, 162.67605634,
          167.6056338 , 172.53521127]]],


       [[[177.46478873, 182.3943662 , 187.32394366, 192.25352113,
          197.18309859, 202.11267606],
         [207.04225352, 211.97183099, 216.90140845, 221.83098592,
          226.76056338, 231.69014085]],

        [[236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
          256.33802817, 261.26760563],
         [266.1971831 , 271.12676056, 276.056

In [81]:
ar = arr.reshape(2, 3, -1)
ar

array([[[  0.        ,   4.92957746,   9.85915493,  14.78873239,
          19.71830986,  24.64788732,  29.57746479,  34.50704225,
          39.43661972,  44.36619718,  49.29577465,  54.22535211],
        [ 59.15492958,  64.08450704,  69.01408451,  73.94366197,
          78.87323944,  83.8028169 ,  88.73239437,  93.66197183,
          98.5915493 , 103.52112676, 108.45070423, 113.38028169],
        [118.30985915, 123.23943662, 128.16901408, 133.09859155,
         138.02816901, 142.95774648, 147.88732394, 152.81690141,
         157.74647887, 162.67605634, 167.6056338 , 172.53521127]],

       [[177.46478873, 182.3943662 , 187.32394366, 192.25352113,
         197.18309859, 202.11267606, 207.04225352, 211.97183099,
         216.90140845, 221.83098592, 226.76056338, 231.69014085],
        [236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
         256.33802817, 261.26760563, 266.1971831 , 271.12676056,
         276.05633803, 280.98591549, 285.91549296, 290.84507042],
        [295.77464

In [82]:
ar = arr.reshape(6, -1)
ar

array([[  0.        ,   4.92957746,   9.85915493,  14.78873239,
         19.71830986,  24.64788732,  29.57746479,  34.50704225,
         39.43661972,  44.36619718,  49.29577465,  54.22535211],
       [ 59.15492958,  64.08450704,  69.01408451,  73.94366197,
         78.87323944,  83.8028169 ,  88.73239437,  93.66197183,
         98.5915493 , 103.52112676, 108.45070423, 113.38028169],
       [118.30985915, 123.23943662, 128.16901408, 133.09859155,
        138.02816901, 142.95774648, 147.88732394, 152.81690141,
        157.74647887, 162.67605634, 167.6056338 , 172.53521127],
       [177.46478873, 182.3943662 , 187.32394366, 192.25352113,
        197.18309859, 202.11267606, 207.04225352, 211.97183099,
        216.90140845, 221.83098592, 226.76056338, 231.69014085],
       [236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
        256.33802817, 261.26760563, 266.1971831 , 271.12676056,
        276.05633803, 280.98591549, 285.91549296, 290.84507042],
       [295.77464789, 300.70422535,

In [83]:
arr

array([  0.        ,   4.92957746,   9.85915493,  14.78873239,
        19.71830986,  24.64788732,  29.57746479,  34.50704225,
        39.43661972,  44.36619718,  49.29577465,  54.22535211,
        59.15492958,  64.08450704,  69.01408451,  73.94366197,
        78.87323944,  83.8028169 ,  88.73239437,  93.66197183,
        98.5915493 , 103.52112676, 108.45070423, 113.38028169,
       118.30985915, 123.23943662, 128.16901408, 133.09859155,
       138.02816901, 142.95774648, 147.88732394, 152.81690141,
       157.74647887, 162.67605634, 167.6056338 , 172.53521127,
       177.46478873, 182.3943662 , 187.32394366, 192.25352113,
       197.18309859, 202.11267606, 207.04225352, 211.97183099,
       216.90140845, 221.83098592, 226.76056338, 231.69014085,
       236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
       256.33802817, 261.26760563, 266.1971831 , 271.12676056,
       276.05633803, 280.98591549, 285.91549296, 290.84507042,
       295.77464789, 300.70422535, 305.63380282, 310.56

In [87]:
ar.reshape(-1)

array([  0.        ,   4.92957746,   9.85915493,  14.78873239,
        19.71830986,  24.64788732,  29.57746479,  34.50704225,
        39.43661972,  44.36619718,  49.29577465,  54.22535211,
        59.15492958,  64.08450704,  69.01408451,  73.94366197,
        78.87323944,  83.8028169 ,  88.73239437,  93.66197183,
        98.5915493 , 103.52112676, 108.45070423, 113.38028169,
       118.30985915, 123.23943662, 128.16901408, 133.09859155,
       138.02816901, 142.95774648, 147.88732394, 152.81690141,
       157.74647887, 162.67605634, 167.6056338 , 172.53521127,
       177.46478873, 182.3943662 , 187.32394366, 192.25352113,
       197.18309859, 202.11267606, 207.04225352, 211.97183099,
       216.90140845, 221.83098592, 226.76056338, 231.69014085,
       236.61971831, 241.54929577, 246.47887324, 251.4084507 ,
       256.33802817, 261.26760563, 266.1971831 , 271.12676056,
       276.05633803, 280.98591549, 285.91549296, 290.84507042,
       295.77464789, 300.70422535, 305.63380282, 310.56

# Understanding numpy resize

## What resize does

numpy resize changes the shape of an array and can also change the number of elements.

Unlike reshape, resize can:

* modify the original array
* increase or decrease the total number of elements

If the new size is larger, numpy repeats the original data.

---

## Basic example

```python
import numpy as np

arr = np.array([1, 2, 3, 4])

np.resize(arr, (2, 3))
```

**Output**

```python
[[1 2 3]
 [4 1 2]]
```

The array is expanded to 6 elements, so values repeat.

---

## Increasing size

```python
arr = np.array([1, 2, 3])

resized = np.resize(arr, 7)
print(resized)
```

**Output**

```python
[1 2 3 1 2 3 1]
```

The data repeats to fill the new size.

---

## Decreasing size

```python
arr = np.array([1, 2, 3, 4, 5])

resized = np.resize(arr, 3)
print(resized)
```

**Output**

```python
[1 2 3]
```

Extra elements are discarded.

---

## Important behavior

resize does not preserve structure

It simply fills the new shape in order, repeating data if needed.

---

## In place resize method

There is also an in place version:

```python
arr = np.array([1, 2, 3, 4])

arr.resize((2, 2))
print(arr)
```

**Output**

```python
[[1 2]
 [3 4]]
```

This modifies the original array directly.

---

## Key differences from reshape

reshape:

* keeps total number of elements the same
* does not repeat or remove data
* usually returns a new array

resize:

* can change total number of elements
* repeats or truncates data
* can modify the original array

---

## When to use resize

Use resize when:

* you need a specific shape regardless of original size
* repeating data is acceptable

Avoid resize when:

* data integrity is important
* you do not want duplicated values

---

## Summary

* resize changes both shape and size
* it can repeat or remove data
* it can modify the original array
* it is less strict than reshape and should be used carefully
